### ISSUE TITLE
Fix permissions on incoming synced files from Drive

### ISSUE THREAD

**Issue by agusalex** [agusalex/grive2Docker#2]
When syncing files From Drive to a local folder, it only has read permissions and it should inherit the permissions from the folder it is on.

**Comment by rqi14** [comment]
Hello. Thanks for sharing the docker container and it has been really useful. It will be much better if the read-only bug can be fixed. Is it a bug inherited from grive2 itself?

**Comment by agusalex** [comment]
I'm not sure if the bug comes from grive2, that would be a bummer.
The best-case scenario would be that it gets fixed by doing some chmod on the start script.

**Comment by agusalex** [comment]
could you try the snapshot build? `docker pull agusalex/grive2:snapshot` I pushed some minor changes, tell me if that works :)

**Comment by goni05** [comment]
That didn't seem to work for me.  Permissions still show the same as before.  I think you should check out https://vsupalov.com/docker-shared-permissions/ for adding a PUID and a PGID (maybe even the UMASK) as used by many of the other unraid docker containers use.

**Comment by agusalex** [comment]
damn, sure will check that out! thanks! will try that today and keep you posted

**Comment by agusalex** [comment]
Well, I'm happy to say this is fixed...ish I added a chmod at the end of every run to fix the permissions issue. I know that's not the right way and neither is running containers as root, but I checked out the link you sent me and run into several issues.
At least this works for now, but I'm open if anyone with more experience can get this fixed properly
